// ESTILOS DOS FORMULÁRIOS (Login, Registo, Demo)
formViewContainer: {
width: '100%',
display: 'flex',
justifyContent: 'center',
alignItems: 'center',
minHeight: '60vh',
},
formCard: {
width: '100%',
maxWidth: '480px',
padding: 'clamp(30px, 6vw, 50px)',
borderRadius: '24px',
display: 'flex',
flexDirection: 'column',
boxSizing: 'border-box',
},
formTitle: {
fontSize: '28px',
fontWeight: '700',
marginBottom: '10px',
textAlign: 'center',
},
formSubtitle: {
fontSize: '15px',
color: '#a3a3a3',
marginBottom: '30px',
textAlign: 'center',
lineHeight: '1.5',
},
form: {
display: 'flex',
flexDirection: 'column',
gap: '16px',
},
input: {
width: '100%',
height: '54px',
background: 'rgba(0, 0, 0, 0.5)',
border: '1px solid rgba(255, 255, 255, 0.1)',
borderRadius: '12px',
padding: '0 20px',
color: '#fff',
fontSize: '15px',
outline: 'none',
boxSizing: 'border-box',
},
select: {
width: '100%',
height: '54px',
background: 'rgba(0, 0, 0, 0.5)',
border: '1px solid rgba(255, 255, 255, 0.1)',
borderRadius: '12px',
padding: '0 20px',
color: '#a3a3a3',
fontSize: '15px',
outline: 'none',
boxSizing: 'border-box',
appearance: 'none', // Remove a seta nativa
},
submitBtn: {
height: '54px',
background: '#14b8a6',
color: '#fff',
border: 'none',
borderRadius: '12px',
fontSize: '16px',
fontWeight: '700',
cursor: 'pointer',
marginTop: '10px',
transition: 'all 0.3s',
},
