import fs from 'node:fs';
const read=f=>fs.readFileSync(new URL('../'+f,import.meta.url),'utf8');
const checks=[]; const ok=(n,c)=>checks.push([n,!!c]);
const app=read('src/App.jsx'), prod=read('src/components/Produtos.jsx'), pdv=read('src/components/PDV.jsx'), vendas=read('src/components/Vendas.jsx'), reg=read('src/core/productRegistry.js'), cfg=read('src/components/Configuracoes.jsx'), modal=read('src/components/ZenModal.jsx');
ok('App usa onSnapshot em tempo real',app.includes('onSnapshot(refOperacao'));
ok('Configuração da loja sincroniza em tempo real',app.includes('onSnapshot(refConfig'));
ok('Produto possui trava atômica por transaction',reg.includes('runTransaction'));
ok('SKU e assinatura lógica são protegidos',reg.includes('sku_')&&reg.includes('sig_'));
ok('Cadastro do catálogo reserva identidade',prod.includes('reservarIdentidadeProduto'));
ok('Cadastro rápido PDV reserva identidade',pdv.includes('reservarIdentidadeProduto'));
ok('Produto com histórico é inativado',prod.includes('produtoTemHistorico')&&prod.includes('ativo:false'));
ok('Exclusão exige senha gerencial',prod.includes('senhaGerente'));
ok('Existe modal visual ZenOS',modal.includes('logo-zenos.png'));
ok('PDV usa modal ZenOS',pdv.includes('<ZenModal'));
ok('Alerta de vitrine usa modal ZenOS e não window.confirm',pdv.includes("titulo:'Atenção ao estoque da vitrine'") && !pdv.includes('window.confirm(`⚠️ Esta venda utiliza unidades da VITRINE'));
ok('Voucher possui registro e saldo no V1',app.includes("field: 'vouchers'")&&vendas.includes('saldoBRL'));
ok('Voucher pode ser consumido no PDV',pdv.includes('voucherCodigoInput')&&pdv.includes("status: saldo <= 0.001 ? 'utilizado'"));
ok('Voucher usa modal ZenOS',vendas.includes("titulo:'Voucher gerado'"));

ok('Vendas monta modal ZenOS na tela',vendas.includes('<ZenModal aberto={!!modalZen}'));
ok('Confirmação de estorno não usa window.confirm',!vendas.includes('window.confirm'));
ok('Histórico possui Central de Vouchers',vendas.includes('Central de Vouchers'));
ok('Venda expandida mostra código do voucher de devolução',vendas.includes('dev.voucherCodigo'));
ok('Menu possui edição rápida de identidade',app.includes('Editar nome e logo'));
ok('Configuração possui largura de impressão',cfg.includes('larguraRecibo'));
ok('Configuração permite mostrar logo no recibo',cfg.includes('mostrarLogoRecibo'));
ok('PDV imprime nome configurado da loja',pdv.includes("perfilRecibo.nomeFantasia"));
ok('Vendas reimprime nome configurado da loja',vendas.includes("perfilRecibo.nomeFantasia"));
ok('Produção não é migrada automaticamente',!app.includes('DELETE V1'));
let fail=0; for(const [n,c] of checks){console.log(`${c?'[OK]':'[FALHA]'} ${n}`);if(!c)fail++;} console.log(`\nATT 06.2: ${checks.length-fail}/${checks.length} verificações aprovadas.`); if(fail)process.exit(1);
